### ISSUE TITLE
CHORE > Use consistent column names for id columns

### ISSUE THREAD

**Issue by mkimberlin** [oci-labs/check-ins#208]
We currently have multiple different column name approaches for the naming of identifier columns. We need to settle on a single naming convention. It would seem there are some complexities with using the name `uuid` as that is a type name. I propose that we solidify around a simple `id` column name for our identifier columns.

Def. of Done:

- [ ] a SQL migration has been written to convert the column names for identifier columns in all tables over to `id`
- [ ] all Java entity classes have been altered to reflect the identity column name change
- [ ] all queries and query repository methods have been altered to reflect the identity column name change

**Comment by meyerinj** [comment]
Although I don't disagree with the idea of changing the key field names I should note I did some more digging since I brought this up and it turns out I wasn't quite right. There is a psql module that adds a UUID type, but `uuid` is not a reserved word in the database we currently have.

The module: https://www.postgresql.org/docs/9.1/uuid-ossp.html

**Comment by Bagurp** [comment]
@meyerinj are you working on this? if not, can I pick this?
