### ISSUE TITLE
Implement test coverage requirement on the server component

### ISSUE THREAD

**Issue by mkimberlin** [oci-labs/check-ins#25]
As a cloud engineer, I would like the ability to see the level of coverage the unit tests provide. 
- [ ] Plan how the components (SonarCube, Github Actions) will fit together and work
- [ ] Analyze the plan so we all agree on the deliverables and outcomes in scope
- [ ] Develop the Action and necessary build step to run the coverage
- [ ] Implement the action into the current build process on the pipeline.

**Comment by jorwalk** [comment]
@mkimberlin could you provide some context and any further bits of detail that would help us determine a scope for this issue?

**Comment by mkimberlin** [comment]
@jorwalk looks like you covered it pretty well with your updates. Is there still additional detail here that I can provide or was I too slow?

**Comment by jorwalk** [comment]
@mkimberlin I appreciate the timing on the response. 
It is my understand that as a product owner, that having 24 hours is an understandable expectation to receive a response.

**Comment by jorwalk** [comment]
@Maroju100 - could you please look into this story on SonarCube? We will need to be able to build a docker image and pass it to SonarCube to run, scan and report.

**Comment by bhatiam12** [comment]
@hwilliams314 I was able to run sonarqube analysis on my local and I will list the steps here so anyone watching this issue can replicate:
1) Add these at project level build.gradle -
 ``` 
plugins {
    id "jacoco"
    id "org.sonarqube" version "2.7.1" 
} 
jacocoTestReport {
    reports {
        xml.enabled true

    }
}
```
2) Run sonarqube instance on docker by running `docker run -d --name sonarqube -p 9000:9000 -p 9092:9092 sonarqube`
3) Open `localhost:9000` and login by admin/admin
3) After logging in click ok "Create New Project" and Enter Project Key = "Check-ins" and click next
4) Input a token name and click "Generate a token name" 
5) Then run `./gradlew sonarqube -x test   -Dsonar.projectKey=Checkins-project
-Dsonar.host.url=http://localhost:9000   -Dsonar.login=YOUR TOKEN THAT WAS GENERATED IN STEP 4`
Once you run STEP 5, then page will reload and show you the code analysis on localhost:9000.
![SonarQube](https://user-images.githubusercontent.com/66330160/85368206-723d6b80-b4f0-11ea-875a-182e2715856a.png)

NOTE : I did `sonarqube -x test`  because tests are failing so for now i used this option to generate a report.

**Comment by bhatiam12** [comment]
@hwilliams314  Now that we have this working on local so we can replicate this to GitHub actions as well and have it run analysis as part of our build. Please try and if you need help then let me know.

**Comment by jorwalk** [comment]
@bhatiam12 - great work! I appreciate you listing the steps to replicate.

**Comment by bhatiam12** [comment]
@jorwalk correct, that code I added and commented out because we didn't have a working example for sonarqube. We need to add sonarqube token to GitHub secrets so actions have access to them and @hwilliams314 is looking into it. Once that's done then we can try executing the action.

**Comment by hwilliams314** [comment]
@jorwalk at the top of the gradle-feature.yml file is this code 
```on:
  push:
    branches-ignore:
      - 'master'
      - 'release*'
``` 
which has this whole file fire off for any push other that master or release (I believe - could be wrong)

**Comment by steinkampr** [comment]
ready for closure 6/24
